### ISSUE TITLE
Potential deadlock when manager thread has terminated

### ISSUE THREAD

**Issue by nikhilm** [Bogdanp/racket-resource-pool#2]
Sorry, I don't have an actual working example right now. I was only reading this code to understand the Racket CML model and write my own kill-safe code unrelated to this use case.

I suspect there is a bug in https://github.com/Bogdanp/racket-resource-pool/blob/e5063198cd4c293d8e99c1f445f8acda2d8d7f4f/resource-pool-lib/pool.rkt#L211-L217

If the thread pool is created in this (admittedly non-idiomatic) way:

```racket
(define pool #f)
(parameterize ([current-custodian (make-custodian)])
  (set! pool (make-pool ...))
  ; do things with the pool
  (custodian-shutdown-all (current-custodian)))

; accident!
; try to operate on the pool here
(pool-take! pool)
```

This hits the case where the manager thread is actually terminated due to custodian shutdown, not just suspended.

The `sync` in `dispatch*` should also sync on the manager thread (and raise an error) to handle this.

Thanks!

**Comment by Bogdanp** [comment]
Threads created by `thread/suspend-to-kill` are merely suspended when their last custodian is shut down, just like when they are killed. So, the `thread-resume` call in `pool-evt` correctly revives the manager thread on demand.

For example, this works just fine:

```racket
#lang racket/base

(require data/pool)

(define mu (make-semaphore 1))
(define seq 0)
(define (next)
  (call-with-semaphore mu
    (lambda ()
      (begin0 seq
        (set! seq (add1 seq))))))
(define p
  (parameterize ([current-custodian (make-custodian)])
    (begin0 (make-pool next)
      (custodian-shutdown-all (current-custodian)))))

(sync (system-idle-evt))
(collect-garbage)
(collect-garbage)
(pool-release! p (pool-take! p))
(pool-take! p)
(pool-release! p (pool-take! p))
(pool-take! p)
```

**Comment by nikhilm** [comment]
Thank you. I was missing the `suspend-to-kill`.
